from typing import Iterator, Literal, Optional, Union

__version__: str

Algorithm = Literal["viterbi", "fmm", "bmm", "bimm"]

class Dictionary:
    @staticmethod
    def load(path: str, alpha: float = 0.5, unknown_cost: Optional[float] = None) -> Dictionary: ...
    def __len__(self) -> int: ...
    def __contains__(self, word: str) -> bool: ...
    def cost(self, word: str) -> Optional[float]: ...
    @property
    def unknown_cost(self) -> float: ...
    def save_binary(self, path: str) -> None: ...

class Token:
    @property
    def text(self) -> str: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def type(self) -> str: ...
    def __iter__(self) -> Iterator[Union[str, int]]: ...

class Segmenter:
    def __init__(
        self,
        dictionary: Union[str, Dictionary, None] = None,
        algorithm: Algorithm = "viterbi",
        unknown_cost: Optional[float] = None,
        merge_unknown: bool = True,
        normalize: bool = True,
        lektoo: Literal["separate", "attach"] = "separate",
    ) -> None: ...
    def segment(self, text: str) -> list[str]: ...
    def tokenize(self, text: str) -> list[Token]: ...
    @property
    def unknown_cost(self) -> float: ...

def clusters(text: str) -> list[str]: ...
def normalize(text: str) -> str: ...
